### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'item_id')

### ISSUE THREAD

**Issue by Yannkes** [ChirilRussu/Albion_Market#1]
Hello when refreshing resource price i get this error.

![image](https://github.com/ChirilRussu/Albion_Market/assets/58672233/576ce8b5-95e0-4fa3-acea-9df77f6d6cb1)

**Comment by ChirilRussu** [comment]
Expected as long as you get it after all the cells have been updated. The script tries to pull 250 items, but there's only 101 on the list. So when it gets to 102nd one it errors out and stops.
